<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputPath>..\0Bins\Other\AssetRipper.Processing.Extended\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\0Bins\obj\AssetRipper.Processing.Extended\$(Configuration)\</IntermediateOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AssetRipper.Export.UnityProjects\AssetRipper.Export.UnityProjects.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.PrimaryContent\AssetRipper.Export.PrimaryContent.csproj" />
	</ItemGroup>

</Project>
