namespace uTinyRipper
{
	public static class Config
	{
		/// <summary>
		/// Is assets GUID should be generated by its unique path or randomly
		/// </summary>
		public static bool IsGenerateGUIDByContent { get; set; } = false;
	}
}
