namespace UtinyRipper
{
	public static class Config
	{
		/// <summary>
		/// Is assets GUID should be generated by its content or randomly (may be slow)
		/// </summary>
		public static bool IsGenerateGUIDByContent { get; set; } = false;
		/// <summary>
		/// Does it should log whole info or just numeric data (may slow down the process)
		/// </summary>
		public static bool IsAdvancedLog { get; set; } = true;
		/// <summary>
		/// Should objects get exported with dependencies or without
		/// </summary>
		public static bool IsExportDependencies { get; set; } = true;
#warning TODO: implement
		/// <summary>
		/// Is convert textures to png file format or export in container format?
		/// </summary>
		public static bool IsConvertTexturesToPNG { get; set; } = false;
#warning TODO: implement
		public static bool IsExportTopmostSerializedVersion => true;
	}
}
