<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputPath>..\0Bins\Other\UnityEngine\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\0Bins\obj\UnityEngine\$(Configuration)\</IntermediateOutputPath>
		<NoWarn>$(NoWarn);CS0169</NoWarn><!--Unused field-->
		<NoWarn>$(NoWarn);CS0649</NoWarn><!--Field is never assigned to-->
	</PropertyGroup>

</Project>
