name: DocFX Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/docfx_build.yml"
      - "docs/**"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/docfx_build.yml"
      - "docs/**"
  schedule:
    - cron: "0 0 * * 0" #once per week

# The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs
#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup DocFX
        run: dotnet tool update -g docfx

      - name: Install dependencies
        run: dotnet restore

      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./docs/_site

  deploy:
    if: ${{ ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' ) && github.repository == 'AssetRipper/AssetRipper' }}
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # or specific "vX.X.X" version tag for this action
