name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish -c Release -r win-x64
        working-directory: ./Source/AssetRipper.GUI.Free/

      - name: List Files
        shell: bash
        run: ls -R ./Source/0Bins/AssetRipper.GUI.Free/Release/

      - name: Write compile time
        shell: bash
        run: date -u > ./Source/0Bins/AssetRipper.GUI.Free/Release/win-x64/publish/compile_time.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: AssetRipper_win_x64
          path: |
            ./Source/0Bins/AssetRipper.GUI.Free/Release/win-x64/publish/AssetRipper.GUI.Free.exe
            ./Source/0Bins/AssetRipper.GUI.Free/Release/win-x64/publish/*.dll
            ./Source/0Bins/AssetRipper.GUI.Free/Release/win-x64/publish/compile_time.txt
          if-no-files-found: error
